### ISSUE TITLE
Won't built against Lua >= 5.2

### ISSUE THREAD

**Issue by LiamFry** [openresty/lua-cjson#36]
Will not build in Lua version >= 5.2 because lua_objlen() is used which is 5.1 only. It was [renamed to lua_rawlen() starting in 5.2](https://www.lua.org/manual/5.2/manual.html#8.3)  I can find no statement(s) within the Cjson documentation noting this nor providing/suggesting a workaround.

Build ...
```
lua_cjson.c:743:19: warning: implicit declaration of function 'lua_objlen' is invalid in C99 [-Wimplicit-function-declaration]
            len = lua_objlen(l, -1);
                  ^
1 warning generated.
```
Test ...
`$ lua -e "require 'cjson'"`

Results
```
/usr/local/bin/lua: error loading module 'cjson' from file '/usr/local/lib/lua/5.2/cjson.so':
	dlopen(/usr/local/lib/lua/5.2/cjson.so, 6): Symbol not found: _lua_objlen
  Referenced from: /usr/local/lib/lua/5.2/cjson.so
  Expected in: flat namespace
 in /usr/local/lib/lua/5.2/cjson.so
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: in ?
```

**Comment by agentzh** [comment]
@LiamFry Lua 5.2 and etc are new languages and thus have new incompatible ABIs. They definitely need special treatment and support.

**Comment by peter-evans** [comment]
I've experienced this, too. The latest release seems to break support for Lua 5.3. Specifying version 2.1.0 is a workaround for now.
`luarocks install lua-cjson 2.1.0`

**Comment by peter-evans** [comment]
Just to clarify, even specifying version 2.1.0 still requires you to set the compatibility flag for Lua 5.1 (DLUA_COMPAT_5_1) when you build Lua 5.3. This is normal behavior. What is not normal is that even with the flag set version 2.1.0.6 of lua-cjson does not seem to respect the flag and fails to compile properly.

**Comment by Alloyed** [comment]
Hi, this still seems to be the case even with #49: the last version uploaded to luarocks.org is 2.1.0.6-1, which will run in lua 5.1 but not 5.2/5.3, and downgrading to 2.1.0-1 will cause luajit-based builds to fail (see https://github.com/mpx/lua-cjson/issues/51). 

Is there an expected cadence for when #49 will be included in a new release and will that new release be uploaded to luarocks?

**Comment by agentzh** [comment]
@Alloyed patches welcome!

**Comment by agentzh** [comment]
@Alloyed Thanks for the report. We'll look into this with the help of @leafo.

**Comment by blueowl04** [comment]
Hello, I am a bit confused about the releases and the building/running issues on Lua > 5.1

First, it seems that Lua > 5.1 support was merged in #49. Also there is 2.1.0.8 release available.
However, there are still issues, because 2.1.0.8 doesn't seem to contain @leafo fixes. So please consider making 2.1.0.9 release ASAP.

It would be also very helpful if you could add  lua-cjson-2.1.0.9-1.rockspec and also new lua-cjson.rockspec (for master branch).
And they should be uploaded to LuaRocks, because it still contains the old 2.1.0.6 version that is broken.

**Comment by blueowl04** [comment]
Oh, BTW the release 2.1.0.8 still contains
`#define CJSON_VERSION   "2.1.0.6"`
in lua_cjson.c

**Comment by leafo** [comment]
Closing this issue as we've had support for building in Lua 5.2+ in the master branch for over a year now. (Those versions are also now available on luarocks.org)

Note: there is still not support for Lua 5.3 integers at the time of this comment.
