### ISSUE TITLE
LuaRocks version fails on Lua 5.4

### ISSUE THREAD

**Issue by mna** [openresty/lua-cjson#67]
Hello,

The rockspec published on LuaRocks installs the tag 2.1.0.6 which fails at execution on Lua 5.4:

```
lua_modules/lib/lua/5.4/cjson.so: undefined symbol: lua_objlen
```

There's also a warning at installation time about that:

```
Installing https://luarocks.org/lua-cjson-2.1.0.6-1.src.rock

lua-cjson 2.1.0.6-1 depends on lua >= 5.1 (5.4-1 provided by VM)
gcc -O2 -fPIC -I/usr/include -c lua_cjson.c -o lua_cjson.o
lua_cjson.c: In function 'json_append_data':
lua_cjson.c:743:19: warning: implicit declaration of function 'lua_objlen' [-Wimplicit-function-declaration]
             len = lua_objlen(l, -1);
                   ^
```

When installing from a locally-altered rockspec that removes the tag constraint (i.e. installing HEAD) works without issue. The fix appears to be in commit f5cf829 which was done after both 2.1.0.7 and 2.1.0.8, so I guess ideally a new version should be tagged and published.

Thanks,
Martin

**Comment by graywolf-at-work** [comment]
Could we possible get patch release even if with just this change?

**Comment by hemedani** [comment]
I have the same issues

**Comment by Olical** [comment]
This also fails in Lua 5.3, for what it's worth.

**Comment by Mehgugs** [comment]
why isn't this released? I've had to pin to `2.1.0-1` and thus have lost the ability to encode empty arrays.

**Comment by well-in-that-case** [comment]
Sorry if this is a necro post, but this command works with Lua 5.4:
`luarocks install lua-cjson "CFLAGS=-DLUA_COMPAT_5_3"`

Seen this issue a lot in my circles. Hopefully it helps someone. Keep in mind, CFLAGS will override existing CFLAGS. So reapply whatever (i.e) optimization flag you'd customarily use.

**Comment by Mehgugs** [comment]
This is only a solution in a vacuum. The fact that you cannot reference this library as a dependency on lua >= 5.3 projects without build failure is the issue. You cannot mandate cflags for luarocks dependencies last I checked.

It's probably less hassle to vendor this module as part of your projet at this point.

**Comment by mystery-z** [comment]
@well-in-that-case thanks so much! that worked~

**Comment by leafo** [comment]
Closing this as 2.1.0.9 and 2.1.0.10 are now available in LuaRocks. You can now install this library on modern versions of Lua without any errors.
